### ISSUE TITLE
influxdb 0.8.8 + grafana 2.6.0

### ISSUE THREAD

**Issue by petibonvm** [anryko/grafana-influx-dashboard#48]
Due to functional constraint i need to keep influxdb 0.8.8 and getdash seems not working with grafana 2.6.0.

Could please fix it ?

regards,

**Comment by anryko** [comment]
I detected the issues and you can expect fixes be pushed to influxdb_v0.8 branch by Monday evening. I will also add some enhancements to the existing v0.8 plugins, however the preconfigured plugin amount has grown since then and I do not plan to backport those (due to influxdb query language changes configuration logic was simplified in transition from v0.8 to v0.9). But if there are some particular plugins that you need and those are preconfigured in latest version and are not present in v0.8 branch, I can help porting those.

**Comment by anryko** [comment]
Please test.

**Comment by petibonvm** [comment]
Same result as before, nothing happens.

In grafana log
`2016/03/29 14:53:47 [I] Completed 127.0.0.1 - "GET /db/collectd/query HTTP/1.1" 404 Not Found`

**Comment by anryko** [comment]
In influxdb_v0.8 branch it should not be "GET /db/collectd/query" it should be ""GET /db/collectd/series", so you are probably trying to run master branch of getdash instead of influxdb_v0.8.
Please pay close attention to installation instructions in master branch. It specifically asks to clone the branch for older influxdb version.

```bash
git clone -b influxdb_v0.8 --depth=1 https://github.com/anryko/grafana-influx-dashboard.git
```

Sorry it was not clear. I should probably update branch README too...

**Comment by petibonvm** [comment]
my bad...it's good now. thank you for your support and your reactivity.

**Comment by anryko** [comment]
You are welcome :)
