### ISSUE TITLE
excessive legends for metric cpu

### ISSUE THREAD

**Issue by chenatu** [anryko/grafana-influx-dashboard#77]
For grafana 4.0 cpu plugin, there are many excessive metrics for the same cpu metric.
![image](https://cloud.githubusercontent.com/assets/3303465/20259066/d9a47d0c-aa8d-11e6-809d-77dddd2b5eb9.png)

When edit the graph:
![image](https://cloud.githubusercontent.com/assets/3303465/20259106/1d0047a2-aa8e-11e6-80ff-b9159e2753c4.png)

**Comment by anryko** [comment]
That's because you have 8 cores on your machine and by default collectd is pushing a metric for each individual core.
If you have collectd version >= 5.5, you should use this configuration: https://github.com/anryko/grafana-influx-dashboard/blob/master/examples/collectd.conf.d/cpu.conf
Otherwise, for older collectd version I would suggest: https://github.com/anryko/cpu-collectd-plugin

**Comment by anryko** [comment]
```_.uniq``` behavior changed in new version of lodash, which introduced a bug after migration to Grafana4.
Please check out the last commit and close the issue if problem is solved.

**Comment by anryko** [comment]
If you want to graph default unaggregated collectd cpu metrics per core, you should apply derivative(sum) function to each cpu graph in getdash.conf.js:
```javascript
  plugins.cpu.cpu = {
    'graph': {
      'system': {
        'color': '#EAB839',
        'apply': 'derivative(sum)',
        'alias': '@description'
      },
...
```
It will work OK, just a bit slower, because for your 8 core setup you will work with 8*8 metrics instead of just 8 if those are aggregated beforehand.

**Comment by chenatu** [comment]
Thank you, it solves my problem
